services:
  md-auth:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: md-auth
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - ./.env:/usr/src/app/.env
    environment:
      - ENV=local
    command: air
    depends_on:
      - postgres-db
      - redis-db

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: Pass123
      POSTGRES_DB: maintainerd
    volumes:
      - ../postgres-db:/var/lib/postgresql/data

  redis-db:
    image: redis:7
    container_name: redis-db
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "Pass123"]
    volumes:
      - ../redis-db:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: devuser
      RABBITMQ_DEFAULT_PASS: Pass123
    volumes:
      - ../rabbitmq:/var/lib/rabbitmq

networks:
  default:
    driver: bridge
