FROM golang:1.24.3-alpine

# Install system dependencies
RUN apk add --no-cache bash git make protobuf

# Install goose (migration tool)
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Install air (live reload)
RUN go install github.com/air-verse/air@v1.62.0

# Set working directory
WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY Makefile ./

EXPOSE 8080

CMD ["air"]
