package server

import authv1 "github.com/maintainerd/auth/internal/platform/gen/go/maintainerd/auth"

var grpcServicePermissions = map[string]string{
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "GetDefaultTenant"):       "",
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "GetTenantByIdentifier"):  "",
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "ListTenants"):            "tenant:read",
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "GetTenant"):              "tenant:read",
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "CreateTenant"):           "tenant:create",
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "UpdateTenant"):           "tenant:update",
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "SetTenantStatus"):        "tenant:update",
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "DeleteTenant"):           "tenant:delete",
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "ListTenantMembers"):      "tenant:read",
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "AddTenantMember"):        "tenant:update",
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "UpdateTenantMemberRole"): "tenant:update",
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "RemoveTenantMember"):     "tenant:update",

	grpcMethod(authv1.TenantSettingService_ServiceDesc.ServiceName, "GetRateLimitConfig"):      "tenant-setting:read",
	grpcMethod(authv1.TenantSettingService_ServiceDesc.ServiceName, "UpdateRateLimitConfig"):   "tenant-setting:update",
	grpcMethod(authv1.TenantSettingService_ServiceDesc.ServiceName, "GetAuditConfig"):          "tenant-setting:read",
	grpcMethod(authv1.TenantSettingService_ServiceDesc.ServiceName, "UpdateAuditConfig"):       "tenant-setting:update",
	grpcMethod(authv1.TenantSettingService_ServiceDesc.ServiceName, "GetMaintenanceConfig"):    "tenant-setting:read",
	grpcMethod(authv1.TenantSettingService_ServiceDesc.ServiceName, "UpdateMaintenanceConfig"): "tenant-setting:update",
	grpcMethod(authv1.TenantSettingService_ServiceDesc.ServiceName, "GetFeatureFlags"):         "tenant-setting:read",
	grpcMethod(authv1.TenantSettingService_ServiceDesc.ServiceName, "UpdateFeatureFlags"):      "tenant-setting:update",
	grpcMethod(authv1.ServiceService_ServiceDesc.ServiceName, "GetMyPolicyBundle"):             "",
	grpcMethod(authv1.ServiceService_ServiceDesc.ServiceName, "ListServices"):                  "service:read",
	grpcMethod(authv1.ServiceService_ServiceDesc.ServiceName, "GetService"):                    "service:read",
	grpcMethod(authv1.ServiceService_ServiceDesc.ServiceName, "CreateService"):                 "service:create",
	grpcMethod(authv1.ServiceService_ServiceDesc.ServiceName, "UpdateService"):                 "service:update",
	grpcMethod(authv1.ServiceService_ServiceDesc.ServiceName, "SetServiceStatus"):              "service:update",
	grpcMethod(authv1.ServiceService_ServiceDesc.ServiceName, "DeleteService"):                 "service:delete",
	grpcMethod(authv1.ServiceService_ServiceDesc.ServiceName, "AssignServicePolicy"):           "service:policy:assign",
	grpcMethod(authv1.ServiceService_ServiceDesc.ServiceName, "RemoveServicePolicy"):           "service:policy:remove",
	grpcMethod(authv1.APIService_ServiceDesc.ServiceName, "ListAPIs"):                          "api:read",
	grpcMethod(authv1.APIService_ServiceDesc.ServiceName, "GetAPI"):                            "api:read",
	grpcMethod(authv1.APIService_ServiceDesc.ServiceName, "CreateAPI"):                         "api:create",
	grpcMethod(authv1.APIService_ServiceDesc.ServiceName, "UpdateAPI"):                         "api:update",
	grpcMethod(authv1.APIService_ServiceDesc.ServiceName, "SetAPIStatus"):                      "api:update",
	grpcMethod(authv1.APIService_ServiceDesc.ServiceName, "DeleteAPI"):                         "api:delete",
	grpcMethod(authv1.PermissionService_ServiceDesc.ServiceName, "ListPermissions"):            "permission:read",
	grpcMethod(authv1.PermissionService_ServiceDesc.ServiceName, "GetPermission"):              "permission:read",
	grpcMethod(authv1.PermissionService_ServiceDesc.ServiceName, "CreatePermission"):           "permission:create",
	grpcMethod(authv1.PermissionService_ServiceDesc.ServiceName, "UpdatePermission"):           "permission:update",
	grpcMethod(authv1.PermissionService_ServiceDesc.ServiceName, "SetPermissionStatus"):        "permission:update",
	grpcMethod(authv1.PermissionService_ServiceDesc.ServiceName, "DeletePermission"):           "permission:delete",
	grpcMethod(authv1.PolicyService_ServiceDesc.ServiceName, "ListPolicies"):                   "policy:read",
	grpcMethod(authv1.PolicyService_ServiceDesc.ServiceName, "GetPolicy"):                      "policy:read",
	grpcMethod(authv1.PolicyService_ServiceDesc.ServiceName, "ListPolicyServices"):             "policy:read",
	grpcMethod(authv1.PolicyService_ServiceDesc.ServiceName, "CreatePolicy"):                   "policy:create",
	grpcMethod(authv1.PolicyService_ServiceDesc.ServiceName, "UpdatePolicy"):                   "policy:update",
	grpcMethod(authv1.PolicyService_ServiceDesc.ServiceName, "SetPolicyStatus"):                "policy:update",
	grpcMethod(authv1.PolicyService_ServiceDesc.ServiceName, "DeletePolicy"):                   "policy:delete",
	grpcMethod(authv1.RoleService_ServiceDesc.ServiceName, "ListRoles"):                        "role:read",
	grpcMethod(authv1.RoleService_ServiceDesc.ServiceName, "GetRole"):                          "role:read",
	grpcMethod(authv1.RoleService_ServiceDesc.ServiceName, "CreateRole"):                       "role:create",
	grpcMethod(authv1.RoleService_ServiceDesc.ServiceName, "UpdateRole"):                       "role:update",
	grpcMethod(authv1.RoleService_ServiceDesc.ServiceName, "SetRoleStatus"):                    "role:update",
	grpcMethod(authv1.RoleService_ServiceDesc.ServiceName, "DeleteRole"):                       "role:delete",
	grpcMethod(authv1.RoleService_ServiceDesc.ServiceName, "ListRolePermissions"):              "role:read",
	grpcMethod(authv1.RoleService_ServiceDesc.ServiceName, "AddRolePermissions"):               "role:permission:create",
	grpcMethod(authv1.RoleService_ServiceDesc.ServiceName, "RemoveRolePermission"):             "role:permission:delete",
	grpcMethod(authv1.AuthorizationService_ServiceDesc.ServiceName, "Authorize"):               "",

	grpcMethod(authv1.IdentityProviderService_ServiceDesc.ServiceName, "ListIdentityProviders"):     "idp:read",
	grpcMethod(authv1.IdentityProviderService_ServiceDesc.ServiceName, "GetIdentityProvider"):       "idp:read",
	grpcMethod(authv1.IdentityProviderService_ServiceDesc.ServiceName, "CreateIdentityProvider"):    "idp:create",
	grpcMethod(authv1.IdentityProviderService_ServiceDesc.ServiceName, "UpdateIdentityProvider"):    "idp:update",
	grpcMethod(authv1.IdentityProviderService_ServiceDesc.ServiceName, "SetIdentityProviderStatus"): "idp:update",
	grpcMethod(authv1.IdentityProviderService_ServiceDesc.ServiceName, "DeleteIdentityProvider"):    "idp:delete",

	grpcMethod(authv1.RegistrationFlowService_ServiceDesc.ServiceName, "ListRegistrationFlows"):       "registration-flow:read",
	grpcMethod(authv1.RegistrationFlowService_ServiceDesc.ServiceName, "GetRegistrationFlow"):         "registration-flow:read",
	grpcMethod(authv1.RegistrationFlowService_ServiceDesc.ServiceName, "CreateRegistrationFlow"):      "registration-flow:create",
	grpcMethod(authv1.RegistrationFlowService_ServiceDesc.ServiceName, "UpdateRegistrationFlow"):      "registration-flow:update",
	grpcMethod(authv1.RegistrationFlowService_ServiceDesc.ServiceName, "SetRegistrationFlowStatus"):   "registration-flow:update",
	grpcMethod(authv1.RegistrationFlowService_ServiceDesc.ServiceName, "DeleteRegistrationFlow"):      "registration-flow:delete",
	grpcMethod(authv1.RegistrationFlowService_ServiceDesc.ServiceName, "AssignRegistrationFlowRoles"): "registration-flow:update",
	grpcMethod(authv1.RegistrationFlowService_ServiceDesc.ServiceName, "ListRegistrationFlowRoles"):   "registration-flow:read",
	grpcMethod(authv1.RegistrationFlowService_ServiceDesc.ServiceName, "RemoveRegistrationFlowRole"):  "registration-flow:update",

	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "ListClients"):               "client:read",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "GetClient"):                 "client:read",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "GetClientSecret"):           "client:secret:read",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "RotateClientSecret"):        "client:secret:rotate",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "GetClientConfig"):           "client:config:read",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "CreateClient"):              "client:create",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "UpdateClient"):              "client:update",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "SetClientStatus"):           "client:update",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "DeleteClient"):              "client:delete",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "ListClientURIs"):            "client:uri:read",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "CreateClientURI"):           "client:uri:create",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "UpdateClientURI"):           "client:uri:update",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "DeleteClientURI"):           "client:uri:delete",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "ListClientAPIs"):            "client:api:read",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "AddClientAPIs"):             "client:api:create",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "RemoveClientAPI"):           "client:api:delete",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "ListClientAPIPermissions"):  "client:api:permission:read",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "AddClientAPIPermissions"):   "client:api:permission:create",
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "RemoveClientAPIPermission"): "client:api:permission:delete",

	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "ListAPIKeys"):               "api_key:read",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "GetAPIKey"):                 "api_key:read",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "GetAPIKeyConfig"):           "api_key:read",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "CreateAPIKey"):              "api_key:create",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "UpdateAPIKey"):              "api_key:update",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "SetAPIKeyStatus"):           "api_key:update",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "DeleteAPIKey"):              "api_key:delete",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "ListAPIKeyAPIs"):            "api_key:read",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "AddAPIKeyAPIs"):             "api_key:update",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "RemoveAPIKeyAPI"):           "api_key:update",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "ListAPIKeyAPIPermissions"):  "api_key:read",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "AddAPIKeyAPIPermissions"):   "api_key:update",
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "RemoveAPIKeyAPIPermission"): "api_key:update",

	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "ListUsers"):                    "user:read",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "GetUser"):                      "user:read",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "CreateUser"):                   "user:create",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "UpdateUser"):                   "user:update",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "SetUserStatus"):                "user:update",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "VerifyUserEmail"):              "user:update",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "VerifyUserPhone"):              "user:update",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "CompleteUserAccount"):          "user:update",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "DeleteUser"):                   "user:delete",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "ForceUserPasswordChange"):      "user:update",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "ListUserRoles"):                "user:read",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "ListUserIdentities"):           "user:read",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "AssignUserRoles"):              "user:create",
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "RemoveUserRole"):               "user:create",
	grpcMethod(authv1.UserProfileService_ServiceDesc.ServiceName, "ListUserProfiles"):      "user:read",
	grpcMethod(authv1.UserProfileService_ServiceDesc.ServiceName, "GetUserProfile"):        "user:read",
	grpcMethod(authv1.UserProfileService_ServiceDesc.ServiceName, "CreateUserProfile"):     "user:update",
	grpcMethod(authv1.UserProfileService_ServiceDesc.ServiceName, "UpdateUserProfile"):     "user:update",
	grpcMethod(authv1.UserProfileService_ServiceDesc.ServiceName, "SetDefaultUserProfile"): "user:update",
	grpcMethod(authv1.UserProfileService_ServiceDesc.ServiceName, "DeleteUserProfile"):     "user:delete",
	grpcMethod(authv1.InviteService_ServiceDesc.ServiceName, "SendInvite"):                 "user:invite",

	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "GetMFAConfig"):             "security-setting:read",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateMFAConfig"):          "security-setting:update",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "GetPasswordConfig"):        "security-setting:read",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdatePasswordConfig"):     "security-setting:update",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "GetSessionConfig"):         "security-setting:read",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateSessionConfig"):      "security-setting:update",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "GetThreatConfig"):          "security-setting:read",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateThreatConfig"):       "security-setting:update",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "GetLockoutConfig"):         "security-setting:read",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateLockoutConfig"):      "security-setting:update",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "GetRegistrationConfig"):    "security-setting:read",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateRegistrationConfig"): "security-setting:update",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "GetTokenConfig"):           "security-setting:read",
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateTokenConfig"):        "security-setting:update",

	grpcMethod(authv1.IPRestrictionRuleService_ServiceDesc.ServiceName, "ListIPRestrictionRules"):     "ip-restriction-rule:read",
	grpcMethod(authv1.IPRestrictionRuleService_ServiceDesc.ServiceName, "GetIPRestrictionRule"):       "ip-restriction-rule:read",
	grpcMethod(authv1.IPRestrictionRuleService_ServiceDesc.ServiceName, "CreateIPRestrictionRule"):    "ip-restriction-rule:create",
	grpcMethod(authv1.IPRestrictionRuleService_ServiceDesc.ServiceName, "UpdateIPRestrictionRule"):    "ip-restriction-rule:update",
	grpcMethod(authv1.IPRestrictionRuleService_ServiceDesc.ServiceName, "SetIPRestrictionRuleStatus"): "ip-restriction-rule:update",
	grpcMethod(authv1.IPRestrictionRuleService_ServiceDesc.ServiceName, "DeleteIPRestrictionRule"):    "ip-restriction-rule:delete",

	grpcMethod(authv1.BrandingService_ServiceDesc.ServiceName, "GetBranding"):    "branding:read",
	grpcMethod(authv1.BrandingService_ServiceDesc.ServiceName, "UpdateBranding"): "branding:update",

	grpcMethod(authv1.EmailTemplateService_ServiceDesc.ServiceName, "ListEmailTemplates"):     "email-template:read",
	grpcMethod(authv1.EmailTemplateService_ServiceDesc.ServiceName, "GetEmailTemplate"):       "email-template:read",
	grpcMethod(authv1.EmailTemplateService_ServiceDesc.ServiceName, "CreateEmailTemplate"):    "email-template:create",
	grpcMethod(authv1.EmailTemplateService_ServiceDesc.ServiceName, "UpdateEmailTemplate"):    "email-template:update",
	grpcMethod(authv1.EmailTemplateService_ServiceDesc.ServiceName, "SetEmailTemplateStatus"): "email-template:update",
	grpcMethod(authv1.EmailTemplateService_ServiceDesc.ServiceName, "DeleteEmailTemplate"):    "email-template:delete",

	grpcMethod(authv1.SMSTemplateService_ServiceDesc.ServiceName, "ListSMSTemplates"):     "sms-template:read",
	grpcMethod(authv1.SMSTemplateService_ServiceDesc.ServiceName, "GetSMSTemplate"):       "sms-template:read",
	grpcMethod(authv1.SMSTemplateService_ServiceDesc.ServiceName, "CreateSMSTemplate"):    "sms-template:create",
	grpcMethod(authv1.SMSTemplateService_ServiceDesc.ServiceName, "UpdateSMSTemplate"):    "sms-template:update",
	grpcMethod(authv1.SMSTemplateService_ServiceDesc.ServiceName, "SetSMSTemplateStatus"): "sms-template:update",
	grpcMethod(authv1.SMSTemplateService_ServiceDesc.ServiceName, "DeleteSMSTemplate"):    "sms-template:delete",

	grpcMethod(authv1.EmailConfigService_ServiceDesc.ServiceName, "GetEmailConfig"):    "email-config:read",
	grpcMethod(authv1.EmailConfigService_ServiceDesc.ServiceName, "UpdateEmailConfig"): "email-config:update",
	grpcMethod(authv1.SMSConfigService_ServiceDesc.ServiceName, "GetSMSConfig"):        "sms-config:read",
	grpcMethod(authv1.SMSConfigService_ServiceDesc.ServiceName, "UpdateSMSConfig"):     "sms-config:update",

	grpcMethod(authv1.WebhookEndpointService_ServiceDesc.ServiceName, "ListWebhookEndpoints"):     "webhook-endpoint:read",
	grpcMethod(authv1.WebhookEndpointService_ServiceDesc.ServiceName, "GetWebhookEndpoint"):       "webhook-endpoint:read",
	grpcMethod(authv1.WebhookEndpointService_ServiceDesc.ServiceName, "CreateWebhookEndpoint"):    "webhook-endpoint:create",
	grpcMethod(authv1.WebhookEndpointService_ServiceDesc.ServiceName, "UpdateWebhookEndpoint"):    "webhook-endpoint:update",
	grpcMethod(authv1.WebhookEndpointService_ServiceDesc.ServiceName, "SetWebhookEndpointStatus"): "webhook-endpoint:update",
	grpcMethod(authv1.WebhookEndpointService_ServiceDesc.ServiceName, "DeleteWebhookEndpoint"):    "webhook-endpoint:delete",

	grpcMethod(authv1.AuthEventService_ServiceDesc.ServiceName, "ListAuthEvents"):        "auth_event:read",
	grpcMethod(authv1.AuthEventService_ServiceDesc.ServiceName, "CountAuthEventsByType"): "auth_event:read",
	grpcMethod(authv1.AuthEventService_ServiceDesc.ServiceName, "GetAuthEvent"):          "auth_event:read",

	grpcMethod(authv1.OAuthIntrospectionService_ServiceDesc.ServiceName, "Introspect"): "",
}

var grpcStepUpMethods = map[string]struct{}{
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "SetTenantStatus"):                   {},
	grpcMethod(authv1.TenantService_ServiceDesc.ServiceName, "DeleteTenant"):                      {},
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "GetClientSecret"):                   {},
	grpcMethod(authv1.ClientService_ServiceDesc.ServiceName, "RotateClientSecret"):                {},
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "CreateAPIKey"):                      {},
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "UpdateAPIKey"):                      {},
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "SetAPIKeyStatus"):                   {},
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "DeleteAPIKey"):                      {},
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "AddAPIKeyAPIs"):                     {},
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "RemoveAPIKeyAPI"):                   {},
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "AddAPIKeyAPIPermissions"):           {},
	grpcMethod(authv1.APIKeyService_ServiceDesc.ServiceName, "RemoveAPIKeyAPIPermission"):         {},
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "SetUserStatus"):                       {},
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "DeleteUser"):                          {},
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "ForceUserPasswordChange"):             {},
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "AssignUserRoles"):                     {},
	grpcMethod(authv1.UserService_ServiceDesc.ServiceName, "RemoveUserRole"):                      {},
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateMFAConfig"):          {},
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdatePasswordConfig"):     {},
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateSessionConfig"):      {},
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateThreatConfig"):       {},
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateLockoutConfig"):      {},
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateRegistrationConfig"): {},
	grpcMethod(authv1.SecuritySettingService_ServiceDesc.ServiceName, "UpdateTokenConfig"):        {},
}

func grpcMethod(service string, method string) string {
	return "/" + service + "/" + method
}
